# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# PLAGUE
Plague.create(name: "Arácnidos")
Plague.create(name: "Avispas")
Plague.create(name: "Blatta Oriental y Periplaneta Americana")
Plague.create(name: "Blattella germanica")
Plague.create(name: "Blattella Germanica y Oriental")
Plague.create(name: "Drosofila")
Plague.create(name: "Ephestia elleutella")
Plague.create(name: "Garrapatas")
Plague.create(name: "Hongos y Bacterias")
Plague.create(name: "Hormigas")
Plague.create(name: "Hormigas,Blattellas Oriental y Germánicas")
Plague.create(name: "Insectos reptantes")
Plague.create(name: "Legionella")
Plague.create(name: "Microorganismos")
Plague.create(name: "Mus Musculus")
Plague.create(name: "Mus Musculus y Rattus Norvegicus")
Plague.create(name: "Necrobia Rufines")
Plague.create(name: "Periplaneta americana")
Plague.create(name: "Periplaneta americana")
Plague.create(name: "Pulgas")
Plague.create(name: "Rattus Norvegicus")
Plague.create(name: "Reticulitermes banyulensis")

# ACTIVITY
Activity.create(name: "Alimentación")
Activity.create(name: "Almacen")
Activity.create(name: "Ayuntamiento")
Activity.create(name: "Bar")
Activity.create(name: "Cafeteria")
Activity.create(name: "Carniceria")
Activity.create(name: "Clinica")
Activity.create(name: "Colegio")
Activity.create(name: "Comercio")
Activity.create(name: "Comunidad")
Activity.create(name: "Congelados")
Activity.create(name: "Discoteca")
Activity.create(name: "Edificio")
Activity.create(name: "Farmacia naturalista")
Activity.create(name: "Finca")
Activity.create(name: "Fruteria")
Activity.create(name: "Gasolinera")
Activity.create(name: "Granja")
Activity.create(name: "Mercado")
Activity.create(name: "Nave industrial")
Activity.create(name: "Ocio")
Activity.create(name: "Oficinas")
Activity.create(name: "Panaderia")
Activity.create(name: "Parque")
Activity.create(name: "Pasteleria")
Activity.create(name: "Pescaderia")
Activity.create(name: "Pizzeria")
Activity.create(name: "Residencia")
Activity.create(name: "Restaurante")
Activity.create(name: "Rostiseria")
Activity.create(name: "Solar")
Activity.create(name: "Supermercado")
Activity.create(name: "Taller mecánico")
Activity.create(name: "Tienda")
Activity.create(name: "Vía Pública")
Activity.create(name: "Vivienda")

# SERVICE
Service.create(name: "Todos")
Service.create(name: "Desinsectación")
Service.create(name: "Desinsectación (Control)")
Service.create(name: "Desratización")
Service.create(name: "Desinfección")
Service.create(name: "Tratamiento xilófagos")
Service.create(name: "Tratamiento del agua")
Service.create(name: "Baja Dr")
Service.create(name: "Baja Ds")
Service.create(name: "Baja Dsf")
Service.create(name: "Baja Control")
Service.create(name: "Baja Xilófago")
Service.create(name: "Baja Legionela")
Service.create(name: "Vacio")
Service.create(name: "Control Palomilla")
Service.create(name: "Suministro")
Service.create(name: "Control Agua")
Service.create(name: "Aparatos I. Voladores")
