require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlaguesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Plague. As you add validations to Plague, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlaguesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all plagues as @plagues" do
      plague = Plague.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:plagues)).to eq([plague])
    end
  end

  describe "GET #show" do
    it "assigns the requested plague as @plague" do
      plague = Plague.create! valid_attributes
      get :show, {:id => plague.to_param}, valid_session
      expect(assigns(:plague)).to eq(plague)
    end
  end

  describe "GET #new" do
    it "assigns a new plague as @plague" do
      get :new, {}, valid_session
      expect(assigns(:plague)).to be_a_new(Plague)
    end
  end

  describe "GET #edit" do
    it "assigns the requested plague as @plague" do
      plague = Plague.create! valid_attributes
      get :edit, {:id => plague.to_param}, valid_session
      expect(assigns(:plague)).to eq(plague)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Plague" do
        expect {
          post :create, {:plague => valid_attributes}, valid_session
        }.to change(Plague, :count).by(1)
      end

      it "assigns a newly created plague as @plague" do
        post :create, {:plague => valid_attributes}, valid_session
        expect(assigns(:plague)).to be_a(Plague)
        expect(assigns(:plague)).to be_persisted
      end

      it "redirects to the created plague" do
        post :create, {:plague => valid_attributes}, valid_session
        expect(response).to redirect_to(Plague.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved plague as @plague" do
        post :create, {:plague => invalid_attributes}, valid_session
        expect(assigns(:plague)).to be_a_new(Plague)
      end

      it "re-renders the 'new' template" do
        post :create, {:plague => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested plague" do
        plague = Plague.create! valid_attributes
        put :update, {:id => plague.to_param, :plague => new_attributes}, valid_session
        plague.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested plague as @plague" do
        plague = Plague.create! valid_attributes
        put :update, {:id => plague.to_param, :plague => valid_attributes}, valid_session
        expect(assigns(:plague)).to eq(plague)
      end

      it "redirects to the plague" do
        plague = Plague.create! valid_attributes
        put :update, {:id => plague.to_param, :plague => valid_attributes}, valid_session
        expect(response).to redirect_to(plague)
      end
    end

    context "with invalid params" do
      it "assigns the plague as @plague" do
        plague = Plague.create! valid_attributes
        put :update, {:id => plague.to_param, :plague => invalid_attributes}, valid_session
        expect(assigns(:plague)).to eq(plague)
      end

      it "re-renders the 'edit' template" do
        plague = Plague.create! valid_attributes
        put :update, {:id => plague.to_param, :plague => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested plague" do
      plague = Plague.create! valid_attributes
      expect {
        delete :destroy, {:id => plague.to_param}, valid_session
      }.to change(Plague, :count).by(-1)
    end

    it "redirects to the plagues list" do
      plague = Plague.create! valid_attributes
      delete :destroy, {:id => plague.to_param}, valid_session
      expect(response).to redirect_to(plagues_url)
    end
  end

end
