class Resume
  field :numero_de_hoja, type: String
  field :numero_cliente, type: String
  field :numero_de_orden, type: String
  field :numero_de_servicio, type: String
  field :estado, type: String
  field :nombre_aplicación, type: String
  field :dirección, type: String
  field :población, type: String
  field :provincia, type: String
  field :dpostal, type: String
  field :preguntar_por, type: String
  field :teléfono, type: String
  field :tipo_servicio, type: String
  field :modo_servicio, type: String
  field :area, type: String
  field :plaga, type: String
  field :fecha_tratamiento, type: String
  field :hora_inicio, type: String
  field :hora_fin, type: String
  field :auxiliar_tratamiento, type: String
  field :producto_1, type: String
  field :producto_2, type: String
  field :producto_3, type: String
  field :producto_4, type: String
  field :producto_5, type: String
  field :producto_6, type: String
  field :producto_7, type: String
  field :numero_registro_producto_1, type: String
  field :numero_registro_producto_2, type: String
  field :numero_registro_producto_3, type: String
  field :numero_registro_producto_4, type: String
  field :numero_registro_producto_5, type: String
  field :numero_registro_producto_6, type: String
  field :numero_registro_producto_7, type: String
  field :material_activo_1, type: String
  field :material_activo_2, type: String
  field :material_activo_3, type: String
  field :material_activo_4, type: String
  field :material_activo_5, type: String
  field :material_activo_6, type: String
  field :material_activo_7, type: String
  field :disolución_1, type: String
  field :disolución_2, type: String
  field :disolución_3, type: String
  field :disolución_4, type: String
  field :disolución_5, type: String
  field :disolución_6, type: String
  field :disolución_7, type: String
  field :cantidad_1, type: String
  field :cantidad_2, type: String
  field :cantidad_3, type: String
  field :cantidad_4, type: String
  field :cantidad_5, type: String
  field :cantidad_6, type: String
  field :cantidad_7, type: String
  field :tipo_aplicación_1, type: String
  field :tipo_aplicación_2, type: String
  field :tipo_aplicación_3, type: String
  field :tipo_aplicación_4, type: String
  field :tipo_aplicación_5, type: String
  field :tipo_aplicación_6, type: String
  field :tipo_aplicación_7, type: String
  field :plazo_de_seguridad, type: String
end
